export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS_STARTED = 'GET_USERS_STARTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';